name: Build L4D2 Director Engine

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PySide6 aiohttp requests SQLAlchemy
        pip install pyinstaller
        
    - name: Install UPX
      run: choco install upx

    - name: Compile Executable
      run: pyinstaller --name "L4D2_Director_Engine" --windowed --onefile --exclude-module=PySide6.QtWebEngine --exclude-module=PySide6.QtWebEngineCore --exclude-module=PySide6.QtWebEngineWidgets --exclude-module=PySide6.QtQml --exclude-module=PySide6.QtQuick --exclude-module=PySide6.QtQuickWidgets --exclude-module=PySide6.QtSql --exclude-module=PySide6.QtTest --exclude-module=PySide6.QtBluetooth --exclude-module=PySide6.QtMultimedia --exclude-module=PySide6.QtMultimediaWidgets --exclude-module=PySide6.QtLocation --exclude-module=PySide6.QtPositioning --exclude-module=PySide6.QtSensors --exclude-module=PySide6.Qt3DCore --exclude-module=PySide6.Qt3DRender --exclude-module=PySide6.QtCharts --exclude-module=PySide6.QtDataVisualization --exclude-module=PySide6.QtDesigner --exclude-module=PySide6.QtHelp --exclude-module=PySide6.QtPdf --exclude-module=PySide6.QtPdfWidgets --exclude-module=PySide6.QtScxml --exclude-module=PySide6.QtSpatialAudio --exclude-module=PySide6.QtSvgWidgets --exclude-module=PySide6.QtTextToSpeech --exclude-module=PySide6.QtVirtualKeyboard --exclude-module=PySide6.QtWebSockets --exclude-module=PySide6.QtXml --exclude-module=tkinter --noconfirm main.py
      
    - name: Package Release Files
      run: |
        mkdir release_build
        cp dist/L4D2_Director_Engine.exe release_build/
        cp vpk_dictionary.json release_build/
        cp settings.example.json release_build/

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: L4D2-Director-Windows-Build
        path: release_build/
